<div class="hero-unit">
	<?php 
		if (!isset($username)) {
			$username = '<form style="display: inline-block;" action="/submit" method="POST"><input type="text" placeholder="Stranger" name="username"><input type="submit"></form>';
		}
	?>	
	<h1><?php echo sprintf($this->translate('Hello %s,'), $username); ?></h1>
    <h2><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h2>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Example Application%s on the cloudControl PaaS. You are currently running Zend Framework version %s. This example can serve as a simple starting point for you to begin building your ZF2 application on cloudControl. This example app is based on the official ZF2 skeleton application but modified to read e.g. database credentials from the cloudControl run-time environment. Check the %scloudControl ZF2 guide%s for more details.'), '<a href="https://github.com/cloudControl/php-zend2-example-app" target="_blank">', '</a>', \Zend\Version\Version::VERSION, '<a href="https://www.cloudcontrol.com/dev-center/Guides/PHP/Zend%202">', '</a>') ?></p>
</div>

</div>
